interface VinculumModule {
  name: string;
  shader: string;
  reads: string[];
  writes: string[];
  flux_producer?: boolean;
  injection_points?: string[];
  requires?: string[];
  injection_rule?: 'auto-on-write' | 'manual';
}

interface VinculumSpec {
  version: string;
  channels: string[];
  modules: Record<string, VinculumModule>;
  compiler: {
    race_detection: { strategy: string; conflict_resolution: string };
    injection: { auto_conserve: boolean; substep_hint: string };
    optimization: { fuse_reads: boolean; prune_unused: boolean };
  };
}

export class VinculumCompiler {
  private spec: VinculumSpec;
  private dag: Map<string, Set<string>> = new Map(); // module -> dependencies

  constructor(spec: VinculumSpec) {
    this.spec = spec;
    this.buildDAG();
    this.validateNoRaces();
  }

  private buildDAG() {
    for (const [name, mod] of Object.entries(this.spec.modules)) {
      this.dag.set(name, new Set(mod.requires || []));
      // Auto-inject conservation if flux_producer writes water/sand
      if (mod.flux_producer && (mod.writes.includes('water') || mod.writes.includes('sand'))) {
        if (!mod.requires?.includes('semi_implicit_conservation')) {
          mod.requires = [...(mod.requires || []), 'semi_implicit_conservation'];
          this.dag.set(name, new Set(mod.requires));
        }
      }
    }
  }

  private validateNoRaces() {
    // Build write-map: channel -> [modules that write it]
    const writeMap = new Map<string, string[]>();
    for (const [name, mod] of Object.entries(this.spec.modules)) {
      for (const ch of mod.writes) {
        if (!writeMap.has(ch)) writeMap.set(ch, []);
        writeMap.get(ch)!.push(name);
      }
    }
    // Check for write-write conflicts without ordering
    for (const [ch, writers] of writeMap) {
      if (writers.length > 1) {
        // Ensure all writers are ordered via DAG edges
        for (let i = 0; i < writers.length; i++) {
          for (let j = i + 1; j < writers.length; j++) {
            if (!this.isOrdered(writers[i], writers[j]) && 
                !this.isOrdered(writers[j], writers[i])) {
              throw new Error(
                `Race condition on channel '${ch}': ` +
                `'${writers[i]}' and '${writers[j]}' both write without ordering`
              );
            }
          }
        }
      }
    }
  }

  private isOrdered(a: string, b: string): boolean {
    // DFS to check if a precedes b in DAG
    const visited = new Set<string>();
    const stack = [a];
    while (stack.length) {
      const curr = stack.pop()!;
      if (curr === b) return true;
      if (visited.has(curr)) continue;
      visited.add(curr);
      for (const dep of this.dag.get(curr) || []) {
        stack.push(dep);
      }
    }
    return false;
  }

  public generateDispatchCode(): string {
    // Topological sort of DAG
    const order = this.topoSort();
    
    // Generate WebGPU dispatch sequence
    let code = `// Auto-generated by Vinculum Compiler v${this.spec.version}\n`;
    code += `const dispatchSequence = [\n`;
    
    for (const modName of order) {
      const mod = this.spec.modules[modName];
      code += `  { name: '${modName}', shader: '${mod.shader}', binds: this.setupBindGroup('${modName}') },\n`;
    }
    code += `];\n`;
    
    // Inject adaptive substep hint if high-flux modules present
    if (this.spec.compiler.injection.substep_hint === 'high-flux') {
      code += `// Hint: enable adaptive substepping for high-flux modules\n`;
      code += `simulationParams.substepThreshold = 0.05;\n`;
    }
    
    return code;
  }

  private topoSort(): string[] {
    // Kahn's algorithm for topological sort
    const inDegree = new Map<string, number>();
    const result: string[] = [];
    const queue: string[] = [];
    
    // Initialize in-degrees
    for (const mod of Object.keys(this.spec.modules)) {
      inDegree.set(mod, 0);
    }
    for (const deps of this.dag.values()) {
      for (const dep of deps) {
        inDegree.set(dep, (inDegree.get(dep) || 0) + 1);
      }
    }
    
    // Start with nodes that have no dependencies
    for (const [mod, deg] of inDegree) {
      if (deg === 0) queue.push(mod);
    }
    
    while (queue.length) {
      const curr = queue.shift()!;
      result.push(curr);
      for (const [mod, deps] of this.dag) {
        if (deps.has(curr)) {
          inDegree.set(mod, inDegree.get(mod)! - 1);
          if (inDegree.get(mod) === 0) queue.push(mod);
        }
      }
    }
    
    if (result.length !== Object.keys(this.spec.modules).length) {
      throw new Error('Cycle detected in Vinculum dependency graph');
    }
    
    return result;
  }
}
