// Auto-generated by Vinculum Compiler v0.1.0
// Pipeline: hyperpoly-terrain

declare const setupBindGroup: (name: string) => any;

export const dispatchSequence = [
  {
    name: 'csg_terraforming',
    shader: 'src/compute/csg_terraforming.wgsl',
    bufferRoles: { input: 'state_A', output: 'state_B' },
    binds: () => setupBindGroup('csg_terraforming')
  },
  {
    name: 'qef_extract',
    shader: 'src/compute/qef_solve.wgsl',
    bufferRoles: { input: 'state_B', output: 'state_B' },
    binds: () => setupBindGroup('qef_extract')
  },
  {
    name: 'advection',
    shader: 'src/compute/advection.wgsl',
    bufferRoles: { input: 'state_B', output: 'state_A' },
    binds: () => setupBindGroup('advection')
  },
  {
    name: 'diffusion',
    shader: 'src/compute/diffusion.wgsl',
    bufferRoles: { input: 'state_A', output: 'state_B' },
    binds: () => setupBindGroup('diffusion')
  },
  {
    name: 'ecosystem_lotka_volterra',
    shader: 'src/compute/lotka_volterra.wgsl',
    bufferRoles: { input: 'state_B', output: 'state_A' },
    binds: () => setupBindGroup('ecosystem_lotka_volterra')
  },
  {
    name: 'semi_implicit_conservation',
    shader: 'src/compute/semi_implicit_conservation.wgsl',
    bufferRoles: { input: 'state_A', output: 'state_B' },
    binds: () => setupBindGroup('semi_implicit_conservation')
  },
];

// Hint: enable adaptive substepping for high-flux modules
export const recommendedSubstepThreshold = 0.05;
